packages:
  - docs
  - playground

shamefullyHoist: true
strictPeerDependencies: false

peerDependencyRules:
  allowedVersions:
    echarts: '6'

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
  workerd: true
